# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Город')),
                ('place', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('birth_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата рождения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='Регистрация')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(verbose_name='Когда?')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location', verbose_name='Что посещал?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User', verbose_name='Кто?')),
            ],
            options={
                'verbose_name': 'посещение',
                'verbose_name_plural': 'посещения',
            },
        ),
    ]
